name: Cimon Detect Mode Audit

on:
  push:
    branches:
      - main

jobs:
  cimon-detect:
    name: Run Cimon in Detect Mode
    runs-on: ubuntu-latest

    steps:
      - uses: cycodelabs/cimon-action@v0
        with:
          report-process-tree: true
          apply-fs-events: true

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Simulate network activity
        run: |
          curl -s https://example.com
          ping -c 1 8.8.8.8
          nslookup github.com

      - name: Simulate file system and process activity
        run: |
          mkdir test_dir
          echo "This is a test file" > test_dir/file.txt
          cat test_dir/file.txt
          ls -la test_dir
          rm -rf test_dir
