name: Semgrep Scan

on:
  push:
    branches:
      - main
      - master
  pull_request: {}
  workflow_dispatch: {}
  schedule:
    - cron: '20 17 * * *'  # Adjust to your preferred scan time

permissions:
  contents: read

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest

    container:
      image: semgrep/semgrep

    if: github.actor != 'dependabot[bot]'

    steps:
      - uses: actions/checkout@v4

      - name: Run Semgrep and save JSON results
        run: semgrep scan --config p/default --json > semgrep_results.json

      - name: Upload JSON results
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-results-json
          path: semgrep_results.json
