name: Trivy Container Scan

on:
  push:
    branches:
      - main
      - master

jobs:
  container_scanning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Trivy vulnerability and license scanner on filesystem
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'json'
          output: 'trivy-results.json'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library,license'  # 👈 Include license scan
          severity: 'MEDIUM'
        continue-on-error: true

      - name: Upload Trivy scan results
        uses: actions/upload-artifact@v4
        with:
          name: trivy-scan-results
          path: trivy-results.json
